import { createClient } from "@supabase/supabase-js";
import { Product, Affiliate, AffiliatePayout, StaffUser, TrainerBankChangeRequest, InventoryBatch } from "./types";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://mock-supplement-factory.supabase.co";
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "mock-anon-key";

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Fallback seed products for immediate interactive UI rendering
export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    sku: "SF-ISO-CHOCO",
    name: "APEX 100% HYDROLYZED WHEY ISOLATE",
    slug: "apex-hydrolyzed-whey-isolate",
    category: "Protein",
    flavor: "Dark Belgian Chocolate",
    size_weight: "5.0 lbs (2.27 kg)",
    price: 34500,
    cost_price: 22000,
    stock: 25,
    reserved_stock: 4, // 21 Available
    description: "Ultra-pure cross-flow micro-filtered whey isolate. 28g Protein, 6.2g BCAAs, zero sugar. Ultra-rapid absorption formulated for peak lean muscle hypertrophy in tropical climates.",
    badge: "BESTSELLER",
    image_url: "https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?auto=format&fit=crop&w=800&q=80",
    is_active: true,
    nutrition_facts: {
      "Protein per Scoop": "28g",
      "BCAAs": "6.2g",
      "Sugar": "0g",
      "Digestive Enzymes": "DigeZyme® Added",
      "Servings": "72 Servings",
    },
  },
  {
    id: "prod-2",
    sku: "SF-PRE-VOLT",
    name: "ANARCHY HIGH-STIM PRE-WORKOUT",
    slug: "anarchy-high-stim-pre-workout",
    category: "Pre-Workout",
    flavor: "Electric Blue Razz",
    size_weight: "40 Servings (400g)",
    price: 18500,
    cost_price: 11000,
    stock: 40,
    reserved_stock: 6, // 34 Available
    description: "Explosive clinical formula engineered with 400mg Caffeine Anhydrous, 6000mg L-Citrulline Malate, and 3200mg Beta-Alanine for laser focus and skin-tearing vascular pumps.",
    badge: "HARDCORE STIM",
    image_url: "https://images.unsplash.com/photo-1593095948071-474c5cc2989d?auto=format&fit=crop&w=800&q=80",
    is_active: true,
    nutrition_facts: {
      "Caffeine Anhydrous": "400mg",
      "L-Citrulline Malate (2:1)": "6,000mg",
      "Beta-Alanine": "3,200mg",
      "Alpha-GPC": "300mg",
      "Servings": "40 Servings",
    },
  },
  {
    id: "prod-3",
    sku: "SF-CREA-MICRO",
    name: "MICRONIZED CREATINE MONOHYDRATE 200 MESH",
    slug: "micronized-creatine-monohydrate",
    category: "Strength",
    flavor: "Pure Unflavored",
    size_weight: "100 Servings (500g)",
    price: 14500,
    cost_price: 7800,
    stock: 60,
    reserved_stock: 12, // 48 Available
    description: "100% pure pharmaceutical grade Creapure® micronized to 200 mesh for maximum solubility and rapid cellular ATP saturation.",
    badge: "ESSENTIAL",
    image_url: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=800&q=80",
    is_active: true,
    nutrition_facts: {
      "Creatine Monohydrate": "5,000mg",
      "Mesh Grade": "200 Mesh Micronized",
      "Purity": "99.9% Lab Tested",
      "Servings": "100 Servings",
    },
  },
  {
    id: "prod-4",
    sku: "SF-MASS-MONSTER",
    name: "TITAN ANABOLIC HEAVYWEIGHT GAINER",
    slug: "titan-anabolic-mass-gainer",
    category: "Mass Gainer",
    flavor: "Vanilla Caramel Cream",
    size_weight: "12.0 lbs (5.44 kg)",
    price: 28900,
    cost_price: 17500,
    stock: 18,
    reserved_stock: 3, // 15 Available
    description: "1,250 clean calories, 65g multi-stage protein matrix, complex carb fuel from rolled oats and sweet potato. Formulated for hardgainers without heavy bloating.",
    badge: "HIGH CALORIE",
    image_url: "https://images.unsplash.com/photo-1546483875-ad9014c88eba?auto=format&fit=crop&w=800&q=80",
    is_active: true,
    nutrition_facts: {
      "Calories": "1,250 kcal",
      "Protein": "65g",
      "Complex Carbohydrates": "240g",
      "MCT Oils": "5g",
      "Servings": "16 Huge Scoops",
    },
  },
];

// Fallback seed affiliates
export const MOCK_AFFILIATES: Affiliate[] = [
  {
    id: "aff-1",
    email: "aqil@supplementfactory.lk",
    password: "coach123",
    trainer_name: "Aqil Rahuman",
    gym_name: "High Octane Fitness (Colombo 07)",
    promo_code: "TRAINER-AQIL10",
    discount_percent: 5,
    commission_rate: 10,
    total_earnings: 145000,
    unpaid_balance: 38500,
    phone: "+94772891234",
    bank_name: "Commercial Bank of Ceylon",
    bank_branch: "Kollupitiya",
    bank_account_no: "8001928374",
    bank_account_name: "A M Aqil Rahuman",
    is_active: true,
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "aff-2",
    email: "shehan@supplementfactory.lk",
    password: "coach123",
    trainer_name: "Shehan Fernando",
    gym_name: "Power World Gyms (Nugegoda)",
    promo_code: "COACH-SHEHAN",
    discount_percent: 5,
    commission_rate: 10,
    total_earnings: 98000,
    unpaid_balance: 24000,
    phone: "+94713456789",
    bank_name: "Sampath Bank",
    bank_branch: "Nugegoda Super Grade",
    bank_account_no: "002345678912",
    bank_account_name: "K S Fernando",
    is_active: true,
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Fallback seed historical payouts
export const MOCK_PAYOUTS: AffiliatePayout[] = [
  {
    id: "pay-1",
    affiliate_id: "aff-1",
    trainer_name: "Aqil Rahuman",
    amount: 50000,
    bank_reference: "COMBANK-FT-889120",
    bank_name: "Commercial Bank of Ceylon",
    bank_account_no: "8001928374",
    notes: "September Week 3 Settlement",
    status: "completed",
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "pay-2",
    affiliate_id: "aff-1",
    trainer_name: "Aqil Rahuman",
    amount: 56500,
    bank_reference: "COMBANK-FT-991204",
    bank_name: "Commercial Bank of Ceylon",
    bank_account_no: "8001928374",
    notes: "September Week 4 Settlement",
    status: "completed",
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "pay-3",
    affiliate_id: "aff-2",
    trainer_name: "Shehan Fernando",
    amount: 74000,
    bank_reference: "SAMPATH-OL-441982",
    bank_name: "Sampath Bank",
    bank_account_no: "002345678912",
    notes: "September Complete Settlement",
    status: "completed",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Fallback seed staff users with granular RBAC privileges
export const MOCK_STAFF_USERS: StaffUser[] = [
  {
    id: "staff-1",
    name: "Roshan Perera",
    email: "roshan@supplementfactory.lk",
    role: "SUPER_ADMIN",
    phone: "+94771122334",
    is_active: true,
    privileges: {
      can_approve_bank_changes: true,
      can_process_payouts: true,
      can_manage_inventory: true,
      can_manage_staff: true,
      can_verify_orders: true,
      can_view_financials: true,
    },
    last_login: new Date().toISOString(),
    created_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "staff-2",
    name: "Dilshan Wickrama",
    email: "dilshan@supplementfactory.lk",
    role: "OPERATIONS_MANAGER",
    phone: "+94773344556",
    is_active: true,
    privileges: {
      can_approve_bank_changes: true,
      can_process_payouts: true,
      can_manage_inventory: true,
      can_manage_staff: false,
      can_verify_orders: true,
      can_view_financials: true,
    },
    last_login: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "staff-3",
    name: "Kavindi Silva",
    email: "kavindi@supplementfactory.lk",
    role: "FINANCE",
    phone: "+94715566778",
    is_active: true,
    privileges: {
      can_approve_bank_changes: true,
      can_process_payouts: true,
      can_manage_inventory: false,
      can_manage_staff: false,
      can_verify_orders: true,
      can_view_financials: true,
    },
    last_login: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "staff-4",
    name: "Asanka Bandara",
    email: "asanka@supplementfactory.lk",
    role: "DISPATCH_STAFF",
    phone: "+94767788990",
    is_active: true,
    privileges: {
      can_approve_bank_changes: false,
      can_process_payouts: false,
      can_manage_inventory: true,
      can_manage_staff: false,
      can_verify_orders: true,
      can_view_financials: false,
    },
    last_login: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Fallback seed trainer bank account change requests (Approval Queue)
export const MOCK_TRAINER_REQUESTS: TrainerBankChangeRequest[] = [
  {
    id: "req-1",
    affiliate_id: "aff-2",
    trainer_name: "Shehan Fernando",
    current_bank_name: "Sampath Bank",
    current_bank_branch: "Nugegoda Super Grade",
    current_bank_account_no: "002345678912",
    current_bank_account_name: "K S Fernando",
    requested_bank_name: "Commercial Bank of Ceylon",
    requested_bank_branch: "Nugegoda City Branch",
    requested_bank_account_no: "8820019283",
    requested_bank_account_name: "K S Fernando",
    requested_phone: "+94713456789",
    reason: "Switching primary business checking account for faster CEFT wire settlements.",
    status: "PENDING",
    created_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
  },
];

// Fallback seed inventory restocking batches (Batch-level Cost and Selling Price Tracking)
export const MOCK_INVENTORY_BATCHES: InventoryBatch[] = [
  {
    id: "batch-1",
    product_id: "prod-1",
    product_name: "APEX 100% HYDROLYZED WHEY ISOLATE",
    product_sku: "SF-ISO-CHOCO",
    quantity_added: 30,
    unit_cost_price: 21500,
    total_cost: 645000,
    selling_price: 34500,
    batch_number: "BATCH-202609-W01",
    supplier_name: "Optimum Labs USA Direct Import",
    notes: "Q3 Sea freight consignment via Colombo Port",
    created_at: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "batch-2",
    product_id: "prod-2",
    product_name: "ANARCHY HIGH-STIM PRE-WORKOUT",
    product_sku: "SF-PRE-VOLT",
    quantity_added: 50,
    unit_cost_price: 10800,
    total_cost: 540000,
    selling_price: 18500,
    batch_number: "BATCH-202609-P02",
    supplier_name: "Anarchy Nutrition UK",
    notes: "Air freight express batch",
    created_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "batch-3",
    product_id: "prod-3",
    product_name: "TITAN MICRONIZED CREATINE MONOHYDRATE",
    product_sku: "SF-CREA-TITAN",
    quantity_added: 60,
    unit_cost_price: 5800,
    total_cost: 348000,
    selling_price: 9900,
    batch_number: "BATCH-202609-C03",
    supplier_name: "Creapure Germany Distributor",
    notes: "200-mesh German Creapure stock",
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "batch-4",
    product_id: "prod-1",
    product_name: "APEX 100% HYDROLYZED WHEY ISOLATE",
    product_sku: "SF-ISO-CHOCO",
    quantity_added: 20,
    unit_cost_price: 22000, // Factory price increased by 500 LKR
    total_cost: 440000,
    selling_price: 34500,
    batch_number: "BATCH-202610-W04",
    supplier_name: "Optimum Labs USA Direct Import",
    notes: "Import tariff adjusted batch (+LKR 500 cost per tub)",
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
